//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEuler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectEuler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 73167176531330624919225119674426574742355349194934
        ///96983520312774506326239578318016984801869478851843
        ///85861560789112949495459501737958331952853208805511
        ///12540698747158523863050715693290963295227443043557
        ///66896648950445244523161731856403098711121722383113
        ///62229893423380308135336276614282806444486645238749
        ///30358907296290491560440772390713810515859307960866
        ///70172427121883998797908792274921901699720888093776
        ///65727333001053367881220235421809751254540594752243
        ///52584907711670556013604839586446706324415722 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem_0008 {
            get {
                return ResourceManager.GetString("Problem_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08
        ///49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00
        ///81 49 31 73 55 79 14 29 93 71 40 67 53 88 30 03 49 13 36 65
        ///52 70 95 23 04 60 11 42 69 24 68 56 01 32 56 71 37 02 36 91
        ///22 31 16 71 51 67 63 89 41 92 36 54 22 40 40 28 66 33 13 80
        ///24 47 32 60 99 03 45 02 44 75 33 53 78 36 84 20 35 17 12 50
        ///32 98 81 28 64 23 67 10 26 38 40 67 59 54 70 66 18 38 64 70
        ///67 26 20 68 02 62 12 20 95 63 94 39 63 08 40 91 66 49 94 21
        ///24 55 58 05 66 73 99 26  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem_0011 {
            get {
                return ResourceManager.GetString("Problem_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 37107287533902102798797998220837590246510135740250
        ///46376937677490009712648124896970078050417018260538
        ///74324986199524741059474233309513058123726617309629
        ///91942213363574161572522430563301811072406154908250
        ///23067588207539346171171980310421047513778063246676
        ///89261670696623633820136378418383684178734361726757
        ///28112879812849979408065481931592621691275889832738
        ///44274228917432520321923589422876796487670272189318
        ///47451445736001306439091167216856844588711603153276
        ///70386486105843025439939619828917593665686757 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem_0013 {
            get {
                return ResourceManager.GetString("Problem_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 75
        ///95 64
        ///17 47 82
        ///18 35 87 10
        ///20 04 82 47 65
        ///19 01 23 75 03 34
        ///88 02 77 73 07 63 67
        ///99 65 04 28 06 16 70 92
        ///41 41 26 56 83 40 80 70 33
        ///41 48 72 33 47 32 37 16 94 29
        ///53 71 44 65 25 43 91 52 97 51 14
        ///70 11 33 28 77 73 17 78 39 68 17 57
        ///91 71 52 38 17 14 91 43 58 50 27 29 48
        ///63 66 04 68 89 53 67 30 73 16 69 87 40 31
        ///04 62 98 27 23 09 70 98 73 93 38 53 60 04 23.
        /// </summary>
        internal static string Problem_0018 {
            get {
                return ResourceManager.GetString("Problem_0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;MARY&quot;,&quot;PATRICIA&quot;,&quot;LINDA&quot;,&quot;BARBARA&quot;,&quot;ELIZABETH&quot;,&quot;JENNIFER&quot;,&quot;MARIA&quot;,&quot;SUSAN&quot;,&quot;MARGARET&quot;,&quot;DOROTHY&quot;,&quot;LISA&quot;,&quot;NANCY&quot;,&quot;KAREN&quot;,&quot;BETTY&quot;,&quot;HELEN&quot;,&quot;SANDRA&quot;,&quot;DONNA&quot;,&quot;CAROL&quot;,&quot;RUTH&quot;,&quot;SHARON&quot;,&quot;MICHELLE&quot;,&quot;LAURA&quot;,&quot;SARAH&quot;,&quot;KIMBERLY&quot;,&quot;DEBORAH&quot;,&quot;JESSICA&quot;,&quot;SHIRLEY&quot;,&quot;CYNTHIA&quot;,&quot;ANGELA&quot;,&quot;MELISSA&quot;,&quot;BRENDA&quot;,&quot;AMY&quot;,&quot;ANNA&quot;,&quot;REBECCA&quot;,&quot;VIRGINIA&quot;,&quot;KATHLEEN&quot;,&quot;PAMELA&quot;,&quot;MARTHA&quot;,&quot;DEBRA&quot;,&quot;AMANDA&quot;,&quot;STEPHANIE&quot;,&quot;CAROLYN&quot;,&quot;CHRISTINE&quot;,&quot;MARIE&quot;,&quot;JANET&quot;,&quot;CATHERINE&quot;,&quot;FRANCES&quot;,&quot;ANN&quot;,&quot;JOYCE&quot;,&quot;DIANE&quot;,&quot;ALICE&quot;,&quot;JULIE&quot;,&quot;HEATHER&quot;,&quot;TER....
        /// </summary>
        internal static string Problem_0022 {
            get {
                return ResourceManager.GetString("Problem_0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A&quot;,&quot;ABILITY&quot;,&quot;ABLE&quot;,&quot;ABOUT&quot;,&quot;ABOVE&quot;,&quot;ABSENCE&quot;,&quot;ABSOLUTELY&quot;,&quot;ACADEMIC&quot;,&quot;ACCEPT&quot;,&quot;ACCESS&quot;,&quot;ACCIDENT&quot;,&quot;ACCOMPANY&quot;,&quot;ACCORDING&quot;,&quot;ACCOUNT&quot;,&quot;ACHIEVE&quot;,&quot;ACHIEVEMENT&quot;,&quot;ACID&quot;,&quot;ACQUIRE&quot;,&quot;ACROSS&quot;,&quot;ACT&quot;,&quot;ACTION&quot;,&quot;ACTIVE&quot;,&quot;ACTIVITY&quot;,&quot;ACTUAL&quot;,&quot;ACTUALLY&quot;,&quot;ADD&quot;,&quot;ADDITION&quot;,&quot;ADDITIONAL&quot;,&quot;ADDRESS&quot;,&quot;ADMINISTRATION&quot;,&quot;ADMIT&quot;,&quot;ADOPT&quot;,&quot;ADULT&quot;,&quot;ADVANCE&quot;,&quot;ADVANTAGE&quot;,&quot;ADVICE&quot;,&quot;ADVISE&quot;,&quot;AFFAIR&quot;,&quot;AFFECT&quot;,&quot;AFFORD&quot;,&quot;AFRAID&quot;,&quot;AFTER&quot;,&quot;AFTERNOON&quot;,&quot;AFTERWARDS&quot;,&quot;AGAIN&quot;,&quot;AGAINST&quot;,&quot;AGE&quot;,&quot;AGENCY&quot;,&quot;AGENT&quot;,&quot;AGO&quot;,&quot;AGREE&quot;,&quot;AGREEMENT&quot;,&quot....
        /// </summary>
        internal static string Problem_0042 {
            get {
                return ResourceManager.GetString("Problem_0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 59
        ///73 41
        ///52 40 09
        ///26 53 06 34
        ///10 51 87 86 81
        ///61 95 66 57 25 68
        ///90 81 80 38 92 67 73
        ///30 28 51 76 81 18 75 44
        ///84 14 95 87 62 81 17 78 58
        ///21 46 71 58 02 79 62 39 31 09
        ///56 34 35 53 78 31 81 18 90 93 15
        ///78 53 04 21 84 93 32 13 97 11 37 51
        ///45 03 81 79 05 18 78 86 13 30 63 99 95
        ///39 87 96 28 03 38 42 17 82 87 58 07 22 57
        ///06 17 51 17 07 93 09 07 75 97 95 78 87 08 53
        ///67 66 59 60 88 99 94 65 55 77 55 34 27 53 78 28
        ///76 40 41 04 87 16 09 42 75 69 23 97 30 60 10 79 87
        ///12 10 44 26 21 36 32 84 98 60 13 12  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Problem_0067 {
            get {
                return ResourceManager.GetString("Problem_0067", resourceCulture);
            }
        }
    }
}
